name: update Indexes

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Firebase Deploy  
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:indexes
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
        

